<?php include_once("header.php"); ?>

<div id="sobre">
    <p>
        <b>Sobrenatural</b> É tudo aquilo que está fora do seu cotidiano e eventualidades do dia a dia. consectetur adipiscing elit. Suspendisse ultrices consequat massa eleifend faucibus. Etiam in nunc nec urna egestas bibendum. Sed id rhoncus tortor. Nunc egestas pellentesque mauris, id fringilla ligula mattis et. Suspendisse sed libero vel enim vehicula gravida. Morbi consectetur vestibulum turpis. Integer nunc justo, cursus eu rhoncus ac, posuere ac lectus. Phasellus a mollis mauris, euismod pretium eros. Nam imperdiet, diam non lobortis facilisis, metus nulla pellentesque dolor, ac scelerisque leo est nec elit. In lacinia malesuada mollis. Nullam eleifend, libero vel tristique posuere, odio elit mollis sapien, eu accumsan dui metus sed lectus. Mauris eget dignissim nulla, in aliquam odio.<br> </br>
        <b> A série</b> é uma das melhores nos dias de hoje, para explicar um puco do que pode existir entre a Terra e o Céu b non vehicula urna rutrum eget. Nam euismod dolor vel magna cursus congue. Morbi ac feugiat elit, at tincidunt neque. Integer turpis dolor, vestibulum vel blandit eu, faucibus in erat. Nunc ut nibh luctus tortor tincidunt accumsan. Praesent suscipit ullamcorper tempus. Praesent at porta nulla. Sed euismod in diam non auctor. Phasellus auctor convallis orci, vel cursus eros tempus at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.<br> </br>
        <b> Demônios</b> cada um tem seu cçador especifico que melhor o conhece volutpat orci. In luctus mauris quam, sed luctus sem laoreet in. Aenean tempor pellentesque ipsum, quis blandit sapien commodo quis. Proin eget consequat ligula, at euismod elit. Duis vitae vulputate arcu. Vestibulum id elementum ligula. Nunc ornare ligula eros, vel placerat mi tristique euismod.<br> </br>        
        <b>Caçadores</b> esses são os que matam e torturam todos os tipos de criaturas presente no nosso planeta ollicitudin nibh. Phasellus sem ipsum, hendrerit sed egestas non, consectetur vel purus. Duis dapibus metus eget felis vulputate, in vulputate erat blandit. Morbi cursus consectetur felis, in tincidunt magna congue et. Cras dapibus congue magna, ut pellentesque nisi consectetur vel. Nam sit amet sollicitudin ipsum, id pulvinar quam. Quisque quis vehicula quam.<br> </br>                
        <b>Curabitur sit amet justo vel libero euismod accumsan.</b> Donec quis porta elit, vitae aliquam odio. Mauris pellentesque augue at nulla scelerisque malesuada. Ut sit amet viverra sapien, hendrerit hendrerit sapien. Suspendisse tortor justo, fringilla nec congue eget, varius id nibh. In at quam vehicula, venenatis magna quis, consequat diam. Morbi vel elit in erat mattis facilisis. 
    </p>
</div>       
<?php
include_once("footer.php");